import {
  Mail,
  Phone,
  MapPin,
  MessageSquare,
  Clock,
  Send,
  ArrowRight,
  Users,
  Award,
  HelpCircle,
  Video,
  Image as ImageIcon,
  Megaphone,
  Search,
  Filter,
  Grid,
  List,
  Play,
  Target,
  Star,
  Lightbulb,
  Calendar,
  Eye,
  Heart,
  BookOpen,
  Plus,
  RefreshCw,
  AlertTriangle,
  Home,
  Check,
  ChevronDown,
  Menu,
  X,
  MapPin as MapPinIcon,
  Camera,
  Instagram,
  Facebook,
  Twitter,
  Youtube,
  Linkedin,
  Link2,
} from "lucide-react";
import { TikTok, WhatsApp } from "@/lib/brand-icons";

export const socialIcons = {
  facebook: Facebook,
  instagram: Instagram,
  twitter: Twitter,
  youtube: Youtube,
  linkedin: Linkedin,
  tiktok: TikTok,
  whatsapp: WhatsApp,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  messageSquare: MessageSquare,
  clock: Clock,
  send: Send,
  arrowRight: ArrowRight,
  users: Users,
  award: Award,
  helpCircle: HelpCircle,
  video: Video,
  image: ImageIcon,
  megaphone: Megaphone,
  search: Search,
  filter: Filter,
  grid: Grid,
  list: List,
  play: Play,
  target: Target,
  star: Star,
  lightbulb: Lightbulb,
  calendar: Calendar,
  eye: Eye,
  heart: Heart,
  bookOpen: BookOpen,
  plus: Plus,
  refreshCw: RefreshCw,
  alertTriangle: AlertTriangle,
  home: Home,
  check: Check,
  chevronDown: ChevronDown,
  menu: Menu,
  x: X,
  mapPinIcon: MapPinIcon,
  camera: Camera,
  link: Link2,
};